### ISSUE TITLE
Compiled Binary

### ISSUE THREAD

**Issue by tomleo** [beeender/glrnvim#1]
Context:

``` console
[~/programs/glrnvim] (master) $ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
[~/programs/glrnvim] (master) $ cargo --version
cargo 1.33.0 (f099fe94b 2019-02-12)
[~/programs/glrnvim] (master) $ rustc --version
rustc 1.33.0 (2aa4c46cf 2019-02-28)
[~/programs/glrnvim] (master) $ cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
[~/programs/glrnvim] (master) $ find /usr/bin/ -iname "glr*"
```

I don't know too much about the rust-lang, and I'm confused as to where the binary ends up. It doesn't seem to be in `/usr/bin/`. Did compilation fail? Is there some type of "make install" step I need to do?

**Comment by beeender** [comment]
After `cargo build`, the binary should be put into `target/debug/glrnvim`.
if you are building the release version with `cargo build --release`, the binary will be `target/release/glrnvim`.
in your case, the full path will be `~/programs/glrnvim/target/debug/glrnvim`.

You can just copy it to `/usr/bin` manually until we have a apt package released.

**Comment by beeender** [comment]
@tomleo I have added `deb` build support.
Please see https://github.com/beeender/glrnvim#debianubuntu for details.

And let me know if it doesn't work.

**Comment by tomleo** [comment]
@beeender That did the trick! Thanks for the help!
