### ISSUE TITLE
Add gvimrc analog to source .gvimrc

### ISSUE THREAD

**Issue by petRUShka** [beeender/glrnvim#20]
It is usually very convenient to have same configuration for both nvim and vim. Usually you just source vim configuration in `init.nvim` or vice versa. 

It is very also convenient to have some gui-based settings in one place. For example that setting can be `background`.

In some nvim guis it is possible to `source ~/.gvimrc` in main config file but it seems that in glrnvim there is `yaml`-config which doesn't suppose to source `viml`-files.

P.S. Also it would be great to have some condition for `if` statement that allows us to understand that we are running glrnvim gui.

**Comment by beeender** [comment]
That would be possible I think. What is the order of sourcing `init.vim` and `.gvimrc` for other vim/nvim client? I expect something like:

```
let g:glrnvim_gui=1
source ~/.config/init.vim
source ~/.config/.gvimrc
```

correct?

**Comment by petRUShka** [comment]
Usually `source ~/.config/init.vim` is done automatically.

Example:
```
$ cat ~/.config/nvim/ginit.vim 
source ~/.vim/gvimrc
if exists('g:GuiLoaded')
    Guifont DejaVu Sans Mono:h15
    " GuiFont! Monospace:h15
endif

cmap <S-Insert>  <C-R>*
```

**Comment by beeender** [comment]
`g:glrnvim_gui=1` is set before nvim sourcing the config in #23 .
Since glrnvim doesn't have the abilities to set font or any other UI configs through VIML, sourcing the `ginit.vim` doesn't seem to be helpful.
I hope this is good enough for this issue.
