### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by geri1701** [beeender/glrnvim#26]
After installing glrnvim from AUR, I get this error message. Can I fix this somehow?

` ~ via 🦀 v1.48.0
❯ RUST_BACKTRACE=full  glrnvim
                                         
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<config::serde_yaml::Value, config::serde_yaml::Value>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0:     0x563c78fd3490 - <unknown>
   1:     0x563c78ff724c - <unknown>
   2:     0x563c78fd0572 - <unknown>
   3:     0x563c78fd576d - <unknown>
   4:     0x563c78fd5418 - <unknown>
   5:     0x563c78fd5e51 - <unknown>
   6:     0x563c78fd59f9 - <unknown>
   7:     0x563c78fd38fc - <unknown>
   8:     0x563c78fd59b9 - <unknown>
   9:     0x563c78ff5b21 - <unknown>
  10:     0x563c78ff5a6d - <unknown>
  11:     0x563c78f04025 - <unknown>
  12:     0x563c78f1a442 - <unknown>
  13:     0x563c78eeee8e - <unknown>
  14:     0x563c78eea337 - <unknown>
  15:     0x563c78ef002a - <unknown>
  16:     0x563c78ee941c - <unknown>
  17:     0x563c78f06a44 - <unknown>
  18:     0x563c78eff265 - <unknown>
  19:     0x563c78f1c383 - <unknown>
  20:     0x563c78f04fa9 - <unknown>
  21:     0x563c78fd6277 - <unknown>
  22:     0x563c78f00f22 - <unknown>
  23:     0x7f76c84e9152 - __libc_start_main
  24:     0x563c78ee90ae - <unknown>
  25:                0x0 - <unknown> `

**Comment by beeender** [comment]
How does your config yaml look like?

**Comment by geri1701** [comment]
Its the example config: 
`# vim:fileencoding=utf-8:ft=yaml`
  
`# Choose the backend terminal to run neovim in.`
`# Current supported terminals: alacritty, urxvt, kitty.`
`#`
`backend: alacritty`
`# path to backend executable file`
`# NOTE: requires a backend key`
`exe_path: /usr/bin/alacritty`

`# The fonts to be used. Multi fonts can be supplied.`
`# The first one will be set as the major font. Others will be set as`
`# fallback fonts according to the given orders if possible.`
`# NOTE: Not all backends support fallback font.`
`fonts:`
`   - Source Code Pro`
`   - monofur`
 
`# The font size to be used.`
`#`
`font_size: 12`
 
`# Set to true if the terminal's default configuration should be loaded`
`# first. Other glrnvim configurations will overwrite the terminal settings`
`# if they are set in glrnvim.yml.`
`# urxvt is not impacted by this setting. It always load resources according`
`# to the defined orders.`
` load_term_conf: true"`

**Comment by beeender** [comment]
After update the rust to the latest version, I can reproduce the issue.

**Comment by beeender** [comment]
The aur has been updated as well. Please just install the `1.1.1`.

**Comment by geri1701** [comment]
Many Thanks!
