### ISSUE TITLE
Incorrect glrnvim version in Cargo.lock makes build to fail when building with nix

### ISSUE THREAD

**Issue by ddrcode** [beeender/glrnvim#28]
I've created a nix script to build glrnvim as a nix package, but the build fails due to mismatch in Cargo.lock. I use v1.1.1 release,  but the Cargo.lock there refers to v1.1.0. According to nix documentation (here: https://nixos.org/manual/nixpkgs/stable/), "_The fetcher will verify that the Cargo.lock file is in sync with the src attribute, and fail the build if not._ "

I know this is rather a hermetic problem, specific to nix, but please remember to make sure in the future releases that the Cargo.lock will be in sync with src. As a quick solution I've forked the project and corrected the version in my fork.

If you're interested - here is my nix build script:
```nix
{ rustPlatform, fetchFromGitHub }:

rustPlatform.buildRustPackage rec {
  name = "glrnvim";
  version = "v1.1.1";

  src = fetchFromGitHub {
    owner = "beeender";
    repo = "glrnvim";
    rev = "${version}";
    sha256 = "1nxxyj4nlvp0rm1vzpn1s6if77sb2k443a2g5x498qm8m3av4714";
  };

  cargoSha256 = "1b50kvl144njngnsr8k6kvnhsns97bcasss0b4v1lrkj01cpzwan";
}
```

If you'd be interested to integrate your project with nix package system or nix os, I'm happy to help.

And on a side note: great work and great idea - I really enjoy using glrnvim!

**Comment by beeender** [comment]
Thanks for reporting this!

> If you'd be interested to integrate your project with nix package system or nix os, I'm happy to help.
Yes, please! I am not sure how does the nix packaging works. Does it need the build script only? In that case, maybe we can create a `pkg` directory and put it there? Also the arch's `PKGBUILD` can be moved there as well.

**Comment by beeender** [comment]
The `Cargo.lock` has been updated and the `v1.1.1` tag has been moved to the latest commit (hope nobody noticed :P )
I guess the nix build can pass with `v1.1.1` now.

**Comment by ddrcode** [comment]
Thank yo so much for fixing the Cargo.lock in v1.1.1 (hope nobody noticed apart besides us :) ). I can confirm everything works perfectly now and compiles. Of course I had to update the SHAs, the script looks as follow now:

```nix
{ rustPlatform, fetchFromGitHub }:

rustPlatform.buildRustPackage rec {
  name = "glrnvim";
  version = "v1.1.2";

  src = fetchFromGitHub {
    owner = "ddrcode";
    repo = "glrnvim";
    rev = "${version}";
    sha256 = "17wbf4pm32kpi2nbphaq3vbhr13alxirwxhpjk7vgvhpnkww1kxn";
  };

  cargoSha256 = "0bqvd52nf986vnhj0hjjmw0s53i1rin1ng6xprggwvfcq4y50hzm";
}
```

In regards making glrnvim available as nix package, we would need to create a PR for nixpackages with a script very similar to the one pasted above - I'm happy to do it for you. Now, after fixing the Cargo.lock, you don't have to do anything on your end.

**Comment by beeender** [comment]
Great! thanks!

**Comment by beeender** [comment]
@all-contributors please add @ddrcode for platform

**Comment by ddrcode** [comment]
Wow, thank you. You can count on me in terms of nix integration
