### ISSUE TITLE
glrnvim failed to run on fedora 33

### ISSUE THREAD

**Issue by Eorclus** [beeender/glrnvim#32]
glrnvim build successfully on fedora 33, but failed to run
cargo 1.49.0
`❯ RUST_BACKTRACE=1 glrnvim
thread 'main' panicked at 'while parsing a block mapping, did not find expected key at line 16 column 3', src/config.rs:53:21
stack backtrace:
   0: std::panicking::begin_panic
             at /builddir/build/BUILD/rustc-1.49.0-src/library/std/src/panicking.rs:521:12
   1: glrnvim::config::parse
             at /home/master-x/glrnvim/src/config.rs:53:21
   2: glrnvim::parse_args
             at /home/master-x/glrnvim/src/main.rs:56:13
   3: glrnvim::main
             at /home/master-x/glrnvim/src/main.rs:121:28
   4: core::ops::function::FnOnce::call_once
             at /builddir/build/BUILD/rustc-1.49.0-src/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

`❯ RUST_BACKTRACE=full ./glrnvim 
thread 'main' panicked at 'while parsing a block mapping, did not find expected key at line 16 column 3', src/config.rs:53:21
stack backtrace:
   0:     0x55b4a70dfbf0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h50fd7129fc8c4dfe
   1:     0x55b4a71041fc - core::fmt::write::ha4ab090616b23b8f
   2:     0x55b4a70dccd5 - std::io::Write::write_fmt::ha42868ce1c3c3ee1
   3:     0x55b4a70e2085 - std::panicking::default_hook::{{closure}}::hdfd3387c4c3e6933
   4:     0x55b4a70e1d28 - std::panicking::default_hook::hcfccb51acd2d6402
   5:     0x55b4a70e2821 - std::panicking::rust_panic_with_hook::h129019d46564370b
   6:     0x55b4a702012b - std::panicking::begin_panic::{{closure}}::hba009c26e81e78d2
   7:     0x55b4a702002c - std::sys_common::backtrace::__rust_end_short_backtrace::h8ef6da159e895865
   8:     0x55b4a700f0b0 - std::panicking::begin_panic::h600b056140b4e87c
   9:     0x55b4a7025fc8 - glrnvim::config::parse::h2dfd5e2e29673009
  10:     0x55b4a700a384 - glrnvim::main::h0897f03094563627
  11:     0x55b4a7020033 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfa0a1113c8d875fb
  12:     0x55b4a700d06d - std::rt::lang_start::{{closure}}::h6d3562b56c649bf9
  13:     0x55b4a70e2c47 - std::rt::lang_start_internal::h0a9d789f0d6c5cb2
  14:     0x55b4a700c222 - main
  15:     0x7fdae35521e2 - __libc_start_main
  16:     0x55b4a6ff30de - _start
  17:                0x0 - <unknown>
`

**Comment by beeender** [comment]
what is  your config file?

**Comment by beeender** [comment]
hmm, I left a comments in the code
https://github.com/beeender/glrnvim/blob/master/src/config.rs#L51
```
// Work around the empty yaml file issue.
// See https://github.com/dtolnay/serde-yaml/issues/86
if e.to_string() != "EOF while parsing a value" {
    panic!(e.to_string())
}
```
So I guess you have an empty config file and due to a recent serde-yaml change, the error message is different now?

**Comment by beeender** [comment]
> while parsing a block mapping, did not find expected key at line 16 column 3

I cannot reproduce this issue, would you please check if your config has any problem at this position?

**Comment by beeender** [comment]
@Eorclus

**Comment by Eorclus** [comment]
ah, yes, I have empty config file, it's working now

**Comment by beeender** [comment]
> ah, yes, I have empty config file, it's working now

hmmm, strange. The hack is supposed to work around the empty config file.
How many blank lines do you have in the config file?
