### ISSUE TITLE
Installation with custom neovim appimage

### ISSUE THREAD

**Issue by LasseWolter** [beeender/glrnvim#38]
I'm wanted to have a newer neovim-version than the debian package manager offers. Thus, I'm using an AppImage from the neovim-release page (https://github.com/neovim/neovim/releases).    
I managed to get glrnvim to work with the AppImage by taking out the `neovim` dependency from the `Cargo.toml` and adding a symlink for `nvim` to my AppImage file. 
I don't think that's a very elegant solution and wanted to ask if there might be a better way to support custom AppImages of neovim :)

**Comment by beeender** [comment]
The neovim dependency is removed from deb build.

**Comment by LasseWolter** [comment]
Nice! Thanks a lot!
