### ISSUE TITLE
No way to recover from suspend

### ISSUE THREAD

**Issue by Netpilgrim** [beeender/glrnvim#4]
Calling :suspend (easily triggered with CTRL-Z) leaves a blank screen in the application window with no obvious way to return to the editor.

As a GUI application this should probably be handled by minimizing the window instead.

**Comment by beeender** [comment]
@Netpilgrim See https://github.com/beeender/glrnvim/commit/810c04597cd5c4a55011adc416abf5185c2daa20 for how to modify the config file to bypass ctrl-z.
