### ISSUE TITLE
Config path

### ISSUE THREAD

**Issue by SuperBo** [beeender/glrnvim#42]
Following the main page, the config file is located in `$HOME/.config/glrnvim.yml`. I think the config file should be `$HOME/.config/glrnvim/config.yml` to follow config standard (each app have their own direcotry such as `$HOME/.config/nvim`.

**Comment by beeender** [comment]
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Looks like you are right. Will change this.

**Comment by LollipopFt** [comment]
hi, will the option in the readme still be available or will i have to change my config path to glrnvim/glrnvim.yml?

**Comment by beeender** [comment]
@LollipopFt Uh, yes, forget to change README. Let me change it and release 1.3.0 :)
For the 1.3.0 (or the build from the latest master), `glrnvim/config.yml` is the right path. The old path `$CONFIG/glrnvim.yml` will still be supported for a while.
