### ISSUE TITLE
'nvim' executable cannot be found.

### ISSUE THREAD

**Issue by LollipopFt** [beeender/glrnvim#45]
i got this error when trying to run glrnvim.exe. do i need to place nvim into path or is there an option to specify the path?

**Comment by LollipopFt** [comment]
another problem:
```
Error: GlrnvimError { message: "None of the suppported terminals can be found." }
```
config:
```yaml
backend: alacritty
exe_path: C:/Users/lollipopft/alacritty
```
on windows btw

**Comment by LollipopFt** [comment]
i solved all the previous problems by placing all of them into path, but last problem: somehow it always opens without it being maximised, and when opened:
i have to run through these settings first:
![image](https://user-images.githubusercontent.com/62802897/134334716-e83d8e28-295c-4c88-ba3e-fc5a0192b85a.png)
and i automatically have 3 tabs open:
![image](https://user-images.githubusercontent.com/62802897/134334612-4e1c9293-56ba-4aa5-8056-44e12c2ea1f3.png)
nvim also does not open in maximised mode.
could i have solutions to these problems please?

**Comment by beeender** [comment]
Uh, windows user! :clap: 
I have never tried glrnvim on windows.

The `exe_path` needs to point to the path of the executable file. I think on windows, it should have an `.exe` extension.

I am thinking below options may work

```
exe_path: C:/Users/lollipopft/alacritty/alacritty.exe
```

```
exe_path: C:\\Users\\lollipopft\\alacritty\\alacritty.exe
```

```
exe_path: C:\Users\lollipopft\alacritty\alacritty.exe
```

**Comment by LollipopFt** [comment]
https://user-images.githubusercontent.com/62802897/134537258-7aec33be-9336-46cf-b9a0-ac621e3fba29.mp4

yeah...

**Comment by beeender** [comment]
Got it. Looks like a bug in Windows. Let me try to get a windows to do some testing

**Comment by LollipopFt** [comment]
> 
> 
> Uh, windows user! 👏
> I have never tried glrnvim on windows.
> 
> The `exe_path` needs to point to the path of the executable file. I think on windows, it should have an `.exe` extension.
> 
> I am thinking below options may work
> 
> ```
> exe_path: C:/Users/lollipopft/alacritty/alacritty.exe
> ```
> 
> ```
> exe_path: C:\\Users\\lollipopft\\alacritty\\alacritty.exe
> ```
> 
> ```
> exe_path: C:\Users\lollipopft\alacritty\alacritty.exe
> ```
> 
> I am not quite sure which seperator does the Rust `PathBuf` recognize on Windows.

it seems like your code did not account for windows paths... none of the suggestions work, including all its variants.

**Comment by beeender** [comment]
The problem which was shown in the video may be related with https://github.com/alacritty/alacritty/issues/3552
