### ISSUE TITLE
Support kitty. Feature

### ISSUE THREAD

**Issue by Donkeyfish87** [beeender/glrnvim#5]
Kitty the terminal use gpu acceleration as well, is it possible to implement that as a feature?

**Comment by beeender** [comment]
Yeah, that would be easy and possible.
The only issue I can imagine right now is the config file -- currently `glrnvim` is just loading a `alacritty` config file.
Maybe we could define a config format and convert it to `kitty`'s or `alacritty`'s when start.

**Comment by beeender** [comment]
will be released in 1.0
