### ISSUE TITLE
nvim-web-devicons  not support  display as  XXXX

### ISSUE THREAD

**Issue by wellcomez** [beeender/glrnvim#51]
https://github.com/kyazdani42/nvim-web-devicons

<img width="730" alt="截屏2021-12-02 下午12 57 35" src="https://user-images.githubusercontent.com/2755665/144360472-96d36051-e56a-4d87-8081-a2559d1ebae3.png">

**Comment by beeender** [comment]
![image](https://user-images.githubusercontent.com/449296/144555163-e7a3d636-6428-4a44-9770-f2f83a78b622.png)

Which icon is not supported? Mine seems to be working fine. And in the screenshot you posted, it seems working as well.

![image](https://user-images.githubusercontent.com/449296/144555267-38dce9f6-f8a8-4757-bc26-9d8b5b76ce67.png)

**Comment by wellcomez** [comment]
> ![image](https://user-images.githubusercontent.com/449296/144555163-e7a3d636-6428-4a44-9770-f2f83a78b622.png)
> 
> Which icon is not supported? Mine seems to be working fine. And in the screenshot you posted, it seems working as well.
> 
> ![image](https://user-images.githubusercontent.com/449296/144555267-38dce9f6-f8a8-4757-bc26-9d8b5b76ce67.png)
<img width="67" alt="截屏2021-12-07 下午4 09 56" src="https://user-images.githubusercontent.com/2755665/144990918-f4399630-63b4-40ae-a8d2-f6d670367ca8.png">

**Comment by wellcomez** [comment]
i use wezterm. 
<img width="395" alt="截屏2021-12-07 下午4 13 24" src="https://user-images.githubusercontent.com/2755665/144991358-ec9a48ea-9387-49de-8a2c-7e13dd150e1d.png">

**Comment by wellcomez** [comment]
> > ![image](https://user-images.githubusercontent.com/449296/144555163-e7a3d636-6428-4a44-9770-f2f83a78b622.png)
> > Which icon is not supported? Mine seems to be working fine. And in the screenshot you posted, it seems working as well.
> > ![image](https://user-images.githubusercontent.com/449296/144555267-38dce9f6-f8a8-4757-bc26-9d8b5b76ce67.png)
> 
> <img alt="截屏2021-12-07 下午4 09 56" width="67" src="https://user-images.githubusercontent.com/2755665/144990918-f4399630-63b4-40ae-a8d2-f6d670367ca8.png">
I know reason ,font 'source code pro' isn't patched
