### ISSUE TITLE
Glrnvim opens an empty buffer on startup instead of my Alpha Dashboard

### ISSUE THREAD

**Issue by shans10** [beeender/glrnvim#57]
I use Alpha to show a dashboard on neovim startup which works everywhere except in glrnvim where it opens an empty buffer instead of my dashboard.

**EXPECTED**
![Screenshot from 2022-08-06 22-36-34](https://user-images.githubusercontent.com/28944997/183258928-6f025348-1a73-42b4-bd44-330831e5710d.png)

**What I get with Glrnvim**
![Screenshot from 2022-08-06 22-36-43](https://user-images.githubusercontent.com/28944997/183258943-604619b1-e75c-4fa4-ab09-85ee92086ced.png)

**System Info**
OS: Arch Linux
DE: Gnome 42.3(Wayland)
Neovim Version: 0.7.2
Glrnvim Version: 1.3.1(Installed from AUR)

**Comment by beeender** [comment]
@shans10 It should be fixed by #58 . Feel free to reopen this if needed.
