### ISSUE TITLE
Working directory of the wrapper process does not follow the child process

### ISSUE THREAD

**Issue by b10n** [beeender/glrnvim#62]
When nvim changes its working directory, the working directory of the wrapper process is not updated.

Steps to reproduce (I'm using Alacritty):

1.  Open glrnvim.
```bash
~ $ glrnvim &
~ $ readlink -e /proc/$(pgrep nvim)/cwd
/home/user
~ $ readlink -e /proc/$(pgrep -f 'alacritty.*nvim')/cwd
/home/user
```
This is expected.

2. Change nvim's working directory: `:cd ~/documents`.
```bash
~ $ readlink -e /proc/$(pgrep nvim)/cwd
/home/user/documents
~ $ readlink -e /proc/$(pgrep -f 'alacritty.*nvim')/cwd
/home/user
```
Here, I expect both processes' working directories to be set to `/home/user/documents`.

This matters for instance when using a script to launch an app in the same directory another window is in.

**Comment by beeender** [comment]
This might not be easy to implement since the terminal doesn't know when the `cd` called in nvim and what is the cwd of the subprocess

> This matters for instance when using a script to launch an app in the same directory another window is in.

Can you share any examples to show the use case? If the script was launched by the nvim, then nvim is its parent process and it should have the same cwd as nvim.

**Comment by b10n** [comment]
> Can you share any examples to show the use case? If the script was launched by the nvim, then nvim is its parent process and it should have the same cwd as nvim.

I meant a script that is launched by the window manager (Sway in my case). Basically my workflow is as follows. When I press a key to open a terminal window, a script runs that determines the working directory of the process of the currently focused window, and then launches a terminal with its working directory set to that same directory. I can work around this issue by instead considering the child nvim process if the currently focused window is glrnvim. I'm aware that this is a pretty niche use case, but there may be others out there that use the glrnvim's working directory for a different purpose.

**Comment by beeender** [comment]
OK, I got it. But I am afraid this would be something that cannot be fixed. To fix this, we need to monitor the nvim CWD and change it accordingly in the terminal process. It seems to be difficult without changing the source of the terminal :(
