### ISSUE TITLE
Alacritty version 0.13 deprecated YAML config

### ISSUE THREAD

**Issue by daniprado** [beeender/glrnvim#68]
Since [Alacritty version 0.13](https://github.com/alacritty/alacritty/releases/tag/v0.13.0), YAML config is deprecated.
This makes it impossible to use glrnvim with Alacritty at the moment as it throws a parse error on the Alacritty config defined inside glrnvim.

Error example:
```
[ERROR] [alacritty_config_derive] Unable to load config "/tmp/.tmpXXXXX": Config error: TOML parse error at line 1, column 4
                                                   |
                                                 1 | ---
                                                   |    ^
                                                 expected `.`, `=`
```

EDIT: Added error message

**Comment by beeender** [comment]
Noticed, will fix this soon. thanks for reporting this!

**Comment by beeender** [comment]
https://github.com/beeender/glrnvim/commit/9a7a54485ac6e09db13f7f6861c680e715b9a5e2

fixed

**Comment by dR3b** [comment]
Will there be a new tag (`v1.4.0`)?

**Comment by beeender** [comment]
@dR3b just release! aur has been updated as well.
