### ISSUE TITLE
What is the font used in the gif ?

### ISSUE THREAD

**Issue by cata0309** [beeender/glrnvim#7]
![image](https://user-images.githubusercontent.com/35623921/63247825-9f851180-c26e-11e9-87e3-03c59cf2371e.png)

Also, can you share you configuration ?

**Comment by beeender** [comment]
Strange, I cannot find the exact font I was using when taking the snapshot.
Could be https://typeof.net/Iosevka/ or https://dejavu-fonts.github.io/

My [init.vim](https://github.com/beeender/glrnvim/files/3530292/init.zip)

**Comment by cata0309** [comment]
Isn't that Mononoki ? I know Iosevka as I use it daily, not similar

**Comment by beeender** [comment]
Yes, it is Mononoki!!! For some reason, it doesn't appear in the gvim's font list. So I didn't see it when I tried to figure out what font it was.

**Comment by cata0309** [comment]
Thank you for confirming my guess
