### ISSUE TITLE
glrnvim not using the kitty config file

### ISSUE THREAD

**Issue by mazenamr** [beeender/glrnvim#8]
glrnvim ignores my kitty config file. For example, I have kitty configured to start with a certain window size, but glrnvim ignores that and uses the default kitty behavior, which is to start with the same window size as the previous instance. It ignores all other configurations, that's just an example.

**Comment by beeender** [comment]
This is designed behaviour. glrnvim will create an kitty config based on its own config file. And won't load the kitty's default config.

I think this can be solved for kitty since it support multiple config merging.

**Comment by beeender** [comment]
fixed in `1.1.0`
use `load_term_conf=true`
